version: '2'
services:
  ui:
    build: ./ui
    ports:
       - '3002:80'
    depends_on:
       - api
  api:
    build: ./api
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '2012:27017'
  janus-gateway:
    build: ./janus
