version: '2'
services:
  ui:
    build: ./ui
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    networks:
      - lib_api
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - lib_api

networks:
  lib_api:
    driver: bridge